### ISSUE TITLE
Encountering Error with OpenAi key

### ISSUE THREAD

**Issue by gunchmode** [jakobdylanc/Discord-LLM-Chatbot#12]
New to all this. Trying to run the script but keep getting this:

Traceback (most recent call last):
  File "C:\Users\Chase\PythonProjects\DiscordLLM\Discord-LLM-Chatbot\llmcord.py", line 19, in <module>
    "api_key": os.environ["OPENAI_API_KEY"],
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'OPENAI_API_KEY'

----

my .env file is exact to your spec with my open ai key recently generated OPENAI_API_KEY =  sk-cswxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by jakobdylanc** [comment]
Are you up-to-date with my latest commit?

Is your .env file definitely named .env and not .env.example?

**Comment by gunchmode** [comment]
.env is named correctly, and I even deleted the example. Attaching screenshots.

OS is Windows 11 pro and steps were as follows:

Copied Repo
created my own .env with updated keys and tokens etc
Installed Python
downloaded Microsoft Visual  C++ tools
pip install --upgrade setuptools
created venv in path
copied -r requirements.txt

then tried to run script and kept running into missing modules and proceeded to install those

pip install discord
pip install dotenv - here's where I ran into issues. Note pad of full code attached below. Mostly errors with setuptools not being in the environment (which I don't get) or depreceated issues with backend dependencies? 


Sorry if all this is dumb
![Screenshot 2024-01-18 190710](https://github.com/jakobdylanc/Discord-LLM-Chatbot/assets/130629469/f281bec9-9cb2-4bd6-b53c-18534ddc9da2)
[DiscordLLM Error Code.txt](https://github.com/jakobdylanc/Discord-LLM-Chatbot/files/13983761/DiscordLLM.Error.Code.txt)

**Comment by jakobdylanc** [comment]
It looks like you're installing the pip packages manually instead of just using my requirements.txt file. You should just run this:

`pip install -r requirements.txt`

As for your error when running `pip install dotenv`, I think it's because the correct command is `pip install python-dotenv`.

**Comment by jakobdylanc** [comment]
If that doesn't work, can you also try messing with the format of your .env? Like changing `OPENAI_API_KEY = XXX` to `OPENAI_API_KEY=XXX` (without spaces). Let me know if this changes anything.

**Comment by gunchmode** [comment]
Negative on all fronts. Dotenv was skipped  "as it is not installed"
successful uninstall and reinstall of python-dotenv and multiple .env format edits, but still recalling that same error:

--- 

 File "C:\Users\Chase\PythonProjects\DiscordLLM\Discord-LLM-Chatbot\llmcord.py", line 19, in <module>
    "api_key": os.environ["OPENAI_API_KEY"],
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'OPENAI_API_KEY'

**Comment by jakobdylanc** [comment]
I think I see the problem now. In the screenshot you sent earlier, notice how your .env file says "Text Document" under the "Type" column:
![image](https://github.com/jakobdylanc/Discord-LLM-Chatbot/assets/38699060/fba0d731-ede3-49ff-90cd-6a460a3da7f4)

I think your ".env" file is actually named ".env.txt" but you have file extensions hidden so you can't see it. Try turning file extensions on to see if this is the case.

**Comment by gunchmode** [comment]
*facepalm 

That was it man! Thank you for the help. Bot is up and running in server now!!

**Comment by jakobdylanc** [comment]
Glad I could help!
