### ISSUE TITLE
Suggestion: Consider adding a conda environment.yml file and containerizing it using Docker

### ISSUE THREAD

**Issue by kourouklides** [jakobdylanc/discord-llm-chatbot#15]
Hey there,

Thank you for helping us to set up your chatbot on our Discord server. It's awesome! Very good job. I am also very glad that you started having traction. I am also trying to spread the word myself.

I would like to suggest the following:
- Adding a **conda** `environment.yml` file (or a similar virtual environment file)
- Adding a `Dockerfile` to use a **Docker** container

Both are good practises, because they ensure that other people who install it do not get the "but it works on my computer" problem.

For example, how would someone know what version of Python he should be using to install this? Also, what version of pip should he be using? Yes, you could write it in your README file, but that's suboptimal. A virtual environment like conda helps eliminate or at least mitigate this problem.

Here's an example of an environmenl.yml from one of my repositories (using Apache License 2.0). I am not saying that it's the best, but it should be good enough to get you started:
- https://github.com/kourouklides/artificial_neural_networks/blob/master/environment.yml

Happy to talk more about it over Discord, if you wish. 🙂

**Comment by jakobdylanc** [comment]
Closing finally as I've decided to keep the repo Docker-free :-)
