### ISSUE TITLE
Loading characters?

### ISSUE THREAD

**Issue by enterv0id** [jakobdylanc/discord-llm-chatbot#18]
Is there any way I can load the character I made in oobabooga webui? 
Really nice job btw, thanks!

**Comment by jakobdylanc** [comment]
I will look into this 👍

**Comment by Avolix** [comment]
This would be a massive thing, character support in general would really enhance this,

**Comment by jakobdylanc** [comment]
Added, enjoy!

**Comment by Avolix** [comment]
Would it be possible for it to be set for it to post the 'Greeting' that a lot of characters make use of if a character is loaded, or as a flag? A lot of them depend on that for context and characterization.

**Comment by jakobdylanc** [comment]
I see what you mean. Unfortunately I don't think character greetings are accessible through oobabooga's API server (which is what my code uses). So not sure how I would do this.

**Comment by Avolix** [comment]
It could be possible for it to load the character itself, and then pass that to ooba. I know sillytavern does it like that, instead of loading the character into ooba itself.

**Comment by jakobdylanc** [comment]
Beyond this it also goes against the functionality of discord-llm-chatbot. The bot is only meant to send messages when responding to a user prompt. Sending an "automatic message" for the greeting doesn't make sense as a feature IMO.

As an alternative you could change the bot's Discord status message to add character context. Just change `github.com/jakobdylanc/discord-llm-chatbot` to whatever you want on this line:
https://github.com/jakobdylanc/discord-llm-chatbot/blob/0d609f3474095f8826692b63394eef5370865670/llmcord.py#L48

**Comment by jakobdylanc** [comment]
> Beyond this it also goes against the functionality of discord-llm-chatbot. The bot is only meant to send messages when responding to a user prompt. Sending an "automatic message" for the greeting doesn't make sense as a feature IMO.
> 
> As an alternative you could write some character context in the bot's Discord activity message. Just change `"github.com/jakobdylanc/discord-llm-chatbot"` to whatever you want on this line:
> 
> https://github.com/jakobdylanc/discord-llm-chatbot/blob/0d609f3474095f8826692b63394eef5370865670/llmcord.py#L48

I just made this easier to do with a new CUSTOM_DISCORD_STATUS config option.
