### ISSUE TITLE
Would it be possible to support different models for images vs. text?

### ISSUE THREAD

**Issue by RustyReich** [jakobdylanc/discord-llm-chatbot#34]
I would like to be able to use a vision model only when the message content includes an image, while using a non-vision model for messages which only include text. Would this be possible?

**Comment by jakobdylanc** [comment]
This is a good suggestion. Definitely possible. I'd have to think more on how to implement this as cleanly as possible. I'm thinking a separate "VISION_LLM" config option, in addition to "LLM".

Regarding the functionality, I think the vision model should be used whenever images are present ANYWHERE in the current conversation, not just the latest message.

**Comment by RustyReich** [comment]
> Regarding the functionality, I think the vision model should be used whenever images are present ANYWHERE in the current conversation, not just the latest message.

I agree, as you may want to continue a discussion about an image that was sent several messages back in the conversation.

**Comment by JzJad** [comment]
May want to check out this: https://github.com/zhaobenny/bz-cogs/tree/main/aiuser (Uses a different model for vision vs text)
I am using it with ollama for a one off questions bot, as it has issues with following a conversation (Yours does an excellent job btw.)
So making this a cog would be awesome too.

**Comment by JzJad** [comment]
Thats precisely the experience I have ran into at least with the smaller models, granted this mostly just helps when using two smaller llm's verse one much larger then both combined.

**Comment by jakobdylanc** [comment]
After much experimenting, I've decided not to implement this.

My larger goal is to allow defining multiple LLMs instead of just 1, and let users manually switch between them with a special command. This would effectively solve this issue.

Hopefully coming soon!

**Comment by MarshallYTHD** [comment]
Unless I understood this [blog post](https://ollama.com/blog/openai-compatibility) wrong, Ollama will be implementing a way to combine a local LLM with chatgpt in the future. It also adds User identity awareness I think? Since its using OpenAI's API.

**Comment by jakobdylanc** [comment]
It won't add user identity awareness because it depends on the LLM being trained to support it. Only OpenAI's models are trained for this; I still haven't seen this support anywhere else.
