### ISSUE TITLE
How to run this

### ISSUE THREAD

**Issue by sigma7eaven** [jakobdylanc/discord-llm-chatbot#35]
How to run this? After set up the instructions trail off into experienced territory us newbs can't get a break what!

**Comment by sigma7eaven** [comment]
It's not clear how to name the .env file? I can't just name it .env?

**Comment by sigma7eaven** [comment]
Ok found python llmcord.py
Now the env file stays as .env.example ?
The instructions are not clear on these to points.

**Comment by sigma7eaven** [comment]
raise KeyError(key) from None
KeyError: 'LLM' 

What this should look like for local api?\

LLM = local/openai/model 

How to set this for oobaboga?

**Comment by jakobdylanc** [comment]
You should create a copy of ".env.example", then rename that copy to ".env". Then populate ".env" with your settings.

**Comment by sigma7eaven** [comment]
![renameenv](https://github.com/jakobdylanc/discord-llm-chatbot/assets/153374531/a72d32e7-71b5-4c03-82ab-583c901b9a36)
The instruction say rename to .env this is not possible do you mean rename .env.example?

**Comment by jakobdylanc** [comment]
Try renaming it to ".env." (with another dot at the end) and Windows should remove the trailing dot and it should work. Sorry about the confusion, I wasn't aware of this behavior on Windows.

**Comment by sigma7eaven** [comment]
> Try renaming it to ".env." (with another dot at the end) and Windows should remove the trailing dot and it should work. Sorry about the confusion, I wasn't aware of this behavior on Windows.

Yes it saved now, I will look at this again and see if we can get it started, thanks.

It's working more it nearly started but maybe need to install PyNaCl? Maybe port conflict I got webui on 7860 Stable Diffusion on 7861? 

Asyncio Loop Issue?

PrivilegedIntentsRequired(exc.shard_id) from None

Now stuck at gateway priviled error.

**Comment by sigma7eaven** [comment]
I had to turn on the many options under privileged consent now it's running but how to get the bot to show up in the server? Should it just arrive automatically? Final instruction how to get the bot into the server? Do I paste this invite link into my browser?

**Comment by sigma7eaven** [comment]
![image](https://github.com/jakobdylanc/discord-llm-chatbot/assets/153374531/eb196660-0a45-4f30-a280-88b3ce6f8bc5)
Here comes the next kick in the pants!

**Comment by sigma7eaven** [comment]
Had to turn of Auth02 Gateway and it works really really well I can't beleive it actually haha this is awesome. 
Thanks for epic app aye.

**Comment by sigma7eaven** [comment]
Thanks for the help and great chat bot.

**Comment by jakobdylanc** [comment]
Glad you got it working! I'll take your feedback into consideration when it comes to setup difficulty. I know the giant table in the README looks intimidating at first and maybe some of the wording could be better.
