### ISSUE TITLE
Can anyone explain this in simple terms why how what who where this problem is coming from?

### ISSUE THREAD

**Issue by sigma7eaven** [jakobdylanc/discord-llm-chatbot#36]
I've searched around but still no clear answer how to avoid this. Every other day it breaks down. One minute ok, turn it off restart and this happens!! How can I prevent this please? Something about reply taking longer than 60 seconds? But it was fine a minute ago.
![image](https://github.com/jakobdylanc/discord-llm-chatbot/assets/153374531/1d0e692a-c49a-40e8-a1cd-b3df4db3a37e)

**Comment by sigma7eaven** [comment]
After I get this error my model wont load anymore in generation webui!

**Comment by sigma7eaven** [comment]
After get this error my webui now takes 5 minutes to load every time!

**Comment by sigma7eaven** [comment]
Sorry I had added Stable Diffusion and it associated plugins were causing a lot of issues. I probably have terrible internet connection in the day time. And lagging out and disconnected. I still fresh at this barely know what I'm doing. I've asked twice how to change that api pointer from open ai is this where problem is coming from it's relaying via open A.I.?

**Comment by jakobdylanc** [comment]
If you have your "LLM" setting set to "local/openai/model" then it's definitely using your local model. Are you still having trouble?
