### ISSUE TITLE
Error Request reply

### ISSUE THREAD

**Issue by Sovann1337** [jakobdylanc/discord-llm-chatbot#40]
Really new to this but i got a few error. I mention the bot than it try to reply but didnt reply. Here is the error
![image](https://github.com/jakobdylanc/discord-llm-chatbot/assets/89128767/7ff0d051-0557-4c58-82e3-f119cb79bdde)
Afterward I got a bunch of error. 
![image](https://github.com/jakobdylanc/discord-llm-chatbot/assets/89128767/2cbbe787-e180-405a-99ad-89cb63e84e8b)
![image](https://github.com/jakobdylanc/discord-llm-chatbot/assets/89128767/17632f58-06ab-401f-8f49-d52bc6aad09e)
DISCORD_BOT_TOKEN = "xxxx"
DISCORD_CLIENT_ID = "xxxxx"
DISCORD_STATUS_MESSAGE = "xxxx"
Here is the only things i edited in the .env file

**Comment by jakobdylanc** [comment]
What do you have "LLM" set to? Also are you using ollama or something else?

**Comment by Sovann1337** [comment]
im kinda new to this but i kept it default. Is there any suggestion for what model should I use? Im not looking forward to pay for openai api stuffs either.

**Comment by Sovann1337** [comment]
I tried switching it to ollama/llama2 just now. But look like i still got the error.
![image](https://github.com/jakobdylanc/discord-llm-chatbot/assets/89128767/945489f8-5ed4-4750-9382-eff1433d963e)

**Comment by jakobdylanc** [comment]
ollama is a separate software that lets you run LLMs locally. You have to install ollama first :)

However I'd recommend using LM Studio instead: https://lmstudio.ai/

Once you're in LM Studio you'll have to download a model and start the Local Inference Server. You can look up guides on how to do this, it's pretty easy.

Then in your .env file for llmcord.py, set "LLM" to `local/openai/model` and set "LOCAL_SERVER_URL" to `http://localhost:1234/v1`. That should be all you need.

**Comment by jakobdylanc** [comment]
LM Studio & ollama is just software to run local models. You still have to choose a model to use. I'd recommend something like llama3-7b.

You won't get something as good as gpt-4o with a local model. It also depends on how strong your computer hardware is. Larger models with better performance require more RAM.

**Comment by Sovann1337** [comment]
Is there any video u would recommend for me to watch since im very clueless on how to setup a local inference server. Beside that i look thru and saw the huggingface site. I was wondering how can i bring the model from the site to the app.

**Comment by jakobdylanc** [comment]
Check out this video: https://www.youtube.com/watch?v=yBI1nPep72Q

He talks about the Local Inference Server around 10 minutes into the video, but I recommend watching the whole thing.

**Comment by jakobdylanc** [comment]
LM Studio has a huggingface browser built into its UI. So you can download models from huggingface directly inside LM Studio.

**Comment by Sovann1337** [comment]
Well cause Im look forward to using the InternVL. But somehow it only has .py file. It doesnt have gguf file. WHich mean im not able to use it?

**Comment by jakobdylanc** [comment]
I'm not sure honestly, I've never used InternVL.

**Comment by Sovann1337** [comment]
Cause Im pretty sure I just downloaded the Llama 3 instruct 7b. I suppose it has the vision function thingie. But when i use the vision thingie in the discord. It got error again. 

Error only the vision right now.

**Comment by maxcurrent420** [comment]
> Cause Im pretty sure I just downloaded the Llama 3 instruct 7b. I suppose it has the vision function thingie. But when i use the vision thingie in the discord. It got error again.
> Error only the vision right now.

You need a vision model to use vision capabilities, and they are of limited usefulness so don't expect OpenAI level accuracy. You will need to download both the LLM (.gguf) and the .mmproj file of the model you want to use. I suggest starting with LM Studio and the mmproj file + the int4 .gguf from here: https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf/tree/main

Then put those in the models folder for LM Studio, and set the chat template to Llama-3-instruct and load the model. Start the server in LM studio and set the endpoint in your .env
