### ISSUE TITLE
possible to add custom messages?

### ISSUE THREAD

**Issue by chaowss** [jakobdylanc/discord-llm-chatbot#41]
I have a use case where I would like to be able to post on behalf of the bot, what would i need to do in order to achieve that? Would it be creating a custom command?

**Comment by jakobdylanc** [comment]
Yeah, a custom command would be the easiest way to do this. There are a few ways to go about this - either the "official" bot command API, or simply look for a specific pattern at the beginning of incoming messages to trigger the command.

I've purposesly avoided adding commands to the bot, so I don't plan to add anything like this.

**Comment by chaowss** [comment]
thank you! great repo btw :)
