### ISSUE TITLE
Why set logger level for litellm? 

### ISSUE THREAD

**Issue by krrishdholakia** [jakobdylanc/discord-llm-chatbot#45]
Hey @jakobdylanc just saw this - 
https://github.com/jakobdylanc/discord-llm-chatbot/blob/9164cf357b5a0cdbfc1206d364b8cadfd6bb4aa5/llmcord.py#L17

curious - why do you need to set the logging level?

**Comment by jakobdylanc** [comment]
Thanks for pointing this out :) there used to be an issue with LiteLLM where, without this, I'd see duplicate log messages in the terminal. But I just re-tested and it looks like it's fixed!

Just removed it: https://github.com/jakobdylanc/discord-llm-chatbot/commit/8395621309cb66e6a109d89b6e812b8af5cce347
