### ISSUE TITLE
Can't see images

### ISSUE THREAD

**Issue by pixelqiwi** [jakobdylanc/discord-llm-chatbot#48]
After loading a model with vision capabilities into LM Studio and sending it an image through Discord it says that it can't see images. 
Is this a limitation on the LM Studio's side or am I actually doing something wrong?

**Comment by jakobdylanc** [comment]
What are you setting LLM to? It should be "local/openai/vision-model".

**Comment by pixelqiwi** [comment]
Ah, yes, my dumb ass was using "local/openai/model", no wonder then. Apologies.
