### ISSUE TITLE
Retreival-Augmented Generation (Suggestion/Development support)

### ISSUE THREAD

**Issue by JurassikLizard** [jakobdylanc/discord-llm-chatbot#52]
I'm going to be implementing a base for RAG using this project.

I was thinking of offering to PR it into this repo.
Are there any design/project structure guidelines to cohere too?

Thanks!
- Jurassik

**Comment by jakobdylanc** [comment]
Sounds cool! I'm curious to know more details.

I'd say don't worry about guidelines; just have fun with it, send the PR and then I can give feedback.
